#ifndef SBL_BUILD_H
#define SBL_BUILD_H

#include "manifest.h"

#define SBL_BUILD_PRODUCT_NAME          TOS_PRODUCT_NAME
#define SBL_BUILD_VERSION               TOS_VERSION
#define SBL_BUILD_VERSION_BOOTLOADER    TOS_BL_VERSION
#define SBL_BUILD_VERSION_BASEBAND      TOS_BB_VERSION

#endif /* SBL_BUILD_H */
