#ifndef TOS_PARTITIONS_H
#define TOS_PARTITIONS_H

#include <stdint.h>

#define TOS_FLASH_BASE              0x08000000UL
#define TOS_FLASH_SIZE              0x00100000UL

#define TOS_PART_ELF_OFFSET         0x00000000UL
#define TOS_PART_ELF_ADDRESS        (TOS_FLASH_BASE + TOS_PART_ELF_OFFSET)
#define TOS_PART_ELF_SIZE           0x00004000UL

#define TOS_PART_SBL_OFFSET         0x00004000UL
#define TOS_PART_SBL_ADDRESS        (TOS_FLASH_BASE + TOS_PART_SBL_OFFSET)
#define TOS_PART_SBL_SIZE           0x00008000UL

#define TOS_PART_TEE_OFFSET         0x0000C000UL
#define TOS_PART_TEE_ADDRESS        (TOS_FLASH_BASE + TOS_PART_TEE_OFFSET)
#define TOS_PART_TEE_SIZE           0x00004000UL
#define TOS_TEE_SIGNATURE_SIZE      0x00003000UL
#define TOS_TEE_STATE_ADDRESS       (TOS_PART_TEE_ADDRESS + TOS_TEE_SIGNATURE_SIZE)
#define TOS_TEE_STATE_SIZE          0x00001000UL

#define TOS_PART_REC_OFFSET         0x00010000UL
#define TOS_PART_REC_ADDRESS        (TOS_FLASH_BASE + TOS_PART_REC_OFFSET)
#define TOS_PART_REC_SIZE           0x00010000UL
#define TOS_REC_COMMAND_SIZE        0x00000400UL
#define TOS_REC_COMMAND_ADDRESS     (TOS_PART_REC_ADDRESS + TOS_PART_REC_SIZE - TOS_REC_COMMAND_SIZE)

#define TOS_PART_SAH_OFFSET         0x00020000UL
#define TOS_PART_SAH_ADDRESS        (TOS_FLASH_BASE + TOS_PART_SAH_OFFSET)
#define TOS_PART_SAH_SIZE           0x00020000UL

#define TOS_PART_SYSTEM_OFFSET      0x00040000UL
#define TOS_PART_SYSTEM_ADDRESS     (TOS_FLASH_BASE + TOS_PART_SYSTEM_OFFSET)
#define TOS_PART_SYSTEM_SIZE        0x00080000UL

#define TOS_PART_TMP_OFFSET         0x000C0000UL
#define TOS_PART_TMP_ADDRESS        (TOS_FLASH_BASE + TOS_PART_TMP_OFFSET)
#define TOS_PART_TMP_SIZE           0x00020000UL
#define TOS_TMP_STAGE_ADDRESS       TOS_PART_TMP_ADDRESS
#define TOS_TMP_STAGE_SIZE          TOS_PART_TMP_SIZE

#define TOS_PART_USERDATA_OFFSET    0x000E0000UL
#define TOS_PART_USERDATA_ADDRESS   (TOS_FLASH_BASE + TOS_PART_USERDATA_OFFSET)
#define TOS_PART_USERDATA_SIZE      0x00020000UL
#define TOS_USERDATA_SETTINGS_SIZE  0x00008000UL
#define TOS_USERDATA_FS_ADDRESS     TOS_PART_USERDATA_ADDRESS
#define TOS_USERDATA_FS_SIZE        TOS_PART_USERDATA_SIZE

#define TOS_SD_INIT_FILE_SIZE       TOS_PART_ELF_SIZE

#define TOS_BOOT_TARGET_NONE             0xFFFFFFFFUL
#define TOS_BOOT_TARGET_FASTBOOT         0x46424F54UL /* FBOT */
#define TOS_BOOT_TARGET_RECOVERY         0x52454356UL /* RECV */
#define TOS_BOOT_TARGET_RECOVERY_FORMAT  0x52464D54UL /* RFMT */
#define TOS_BOOT_TARGET_RECOVERY_UPGRADE 0x52555047UL /* RUPG */
#define TOS_BOOT_TARGET_RECOVERY_INIT    0x52494E49UL /* RINI */

#define TOS_UPDATE_NONE 0UL
#define TOS_UPDATE_SBL  1UL
#define TOS_UPDATE_REC  2UL

#define TOS_TXN_STATE_PENDING 0xFFFFFFFEUL
#define TOS_TXN_STATE_DONE    0xFFFFFFFCUL
#define TOS_TXN_STATE_FAILED  0xFFFFFFF8UL

#endif /* TOS_PARTITIONS_H */
