#ifndef SBL_BUILD_H
#define SBL_BUILD_H

#define SBL_BUILD_PRODUCT_NAME "CNAEK7"
#define SBL_BUILD_VERSION "V1"
#define SBL_BUILD_VERSION_BOOTLOADER "TOSV1.0"
#define SBL_BUILD_VERSION_BASEBAND "N/A"
#define SBL_BUILD_UNLOCKED "no"

#endif /* SBL_BUILD_H */
